apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmf-app
  namespace: acmf-namespace
  labels:
    app: acmf-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: acmf-app
  template:
    metadata:
      labels:
        app: acmf-app
    spec:
      containers:
        - name: acmf-app-container
          image: harshdwivedi295/frridemongo:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
