apiVersion: v1
kind: Service
metadata:
  name: acmf-service
  namespace: acmf-namespace
  labels:
    app: acmf-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: acmf-app
